"""Initial migration.

Revision ID: 48c7ae17a3bb
Revises: 
Create Date: 2024-08-24 20:34:07.108961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c7ae17a3bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complata', sa.Boolean(), nullable=True))
        batch_op.drop_column('complete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('complata')

    # ### end Alembic commands ###
