"""Initial migration.

Revision ID: f8e3b0997455
Revises: 48c7ae17a3bb
Create Date: 2024-08-24 20:35:53.177118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e3b0997455'
down_revision = '48c7ae17a3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complete', sa.Boolean(), nullable=True))
        batch_op.drop_column('complata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complata', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('complete')

    # ### end Alembic commands ###
